### ISSUE TITLE
seed.js file does not create User table/collection is database

### ISSUE THREAD

**Issue by naseemfico** [mosh-hamedani/vidly-api-node#9]
seed.js file does not create User table/collection is database. I am completely stuck and can't move on as other next tutorials are all about logging in and auth.

**Comment by naseemfico** [comment]
its just crazy seeds creates it but still I can't get the endpoint.

**Comment by cyberena** [comment]
Any solutions for this?

**Comment by cyberena** [comment]
Hi, this problem still exists. It seems the github download as of today is incomplete and missing parts which completely hinders the ability to continue the tutorial.  I spent a while to figure it out and this is how you can insert it yourself and then also change the api so that it is readable by the web.

1. Go to command prompt and type "mongo" to enter the shell
2. type "use vidly" to use that db
3. type
db.users.insert(
{
    "name":"Tom Hanks",
    "email":"tom@tom.com",
    "password":"234242"
})

Now youve inserted and created a new collections called "users" with one object

4. Go to vidly-api-node folder and open routes/users.js file

insert this code to top after all the const declarations

router.get("/", async (req, res) => {
  const users = await User.find();
  res.send(users);
});


5. restart node using the "node index.js" command

6. use postman and do a test call to 
http://localhost:3900/api/users

It works.  

Dear Mosh, your tutorials are awesome, can you please fix this so people can finish them and recommend you even more around the world.  Thank you.

**Comment by cyberena** [comment]
@naseemfico  can you please REOPEN this issue since it still exists

**Comment by naseemfico** [comment]
I believe this issue was fixed after reinstalling different verison of bycrpt. I just followed the on screen npm recommendation which resolved the issue. I don't exactly remember what version was that but it popped up.

**Comment by cyberena** [comment]
No thats a different issue you can see by clicking here:
https://github.com/mosh-hamedani/vidly-api-node/issues/2

Installing diff version fixed that, but this bug that you reported still exists in latest github. If you study the code seed.js , youll see it DOES NOT popular the users.

**Comment by Linlin-Sun** [comment]
Thanks a lot for the help here.
